########################################## DATASET RELATED ##########################################
raw_train_csvs: 
  - train_file_1
  - train_file_2
result_train_csv: result_train_file
raw_test_csvs:
  - test_file_1
  - test_file_2
result_test_csv: result_test_file

########################################### MODEL RELATED ###########################################
search_params_file: search_params_file
json_results_dir: json_results_dir

############################################ DWF RELATED ############################################
dbh_path : dbh_path